### ISSUE TITLE
duplicates

### ISSUE THREAD

**Issue by rbarbrow** [winget-run/wingetdotrun#4] opened 2021-06-08 12:06 UTC
https://winget.run/pkg/Microsoft/PowerShell-Preview-MSIX

and

https://winget.run/pkg/microsoft/powershell-preview-msix

appear to be the same thing just with different case but show as two different cards

**Comment by Dragon1320** [comment] 2021-12-24 15:48
May have been caused by our outdated package db, should be fixed now, if the issue persists, feel free to reopen.

**Closed by Dragon1320** 2021-12-24 15:48 UTC
